name: iOS-Trading-App
options:
  bundleIdPrefix: com.example

targets:
  iOS-Trading-App:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iOS-Trading-AppApp.swift
      - path: ContentView.swift
      - path: Config.swift
      - path: WebSocketManager.swift
      - path: NewsAPIClient.swift
      - path: ZerodhaAPIClient.swift
      - path: DataProviders.swift
      - path: ZerodhaAuthManager.swift
      - path: KeychainHelper.swift
      - path: DataModels.swift
      - path: DataSyncManager.swift
      - path: DataValidator.swift
      - path: DataConnectionManager.swift
      - path: HistoricalDataEngine.swift
      - path: TechnicalAnalysisEngine.swift
      - path: RiskManagementAgent.swift
      - path: StrategySelectionAgent.swift
      - path: MarketAnalysisAgent.swift
      - path: SentimentAnalyzer.swift
      - path: MLModelManager.swift
      - path: VirtualPortfolio.swift
      - path: OrderExecutor.swift
      - path: PLCalculator.swift
      - path: PaperTradingView.swift
      - path: AIAgentTrader.swift
      - path: BacktestingEngine.swift
      - path: BacktestingView.swift
      - path: AdvancedRiskManager.swift
      - path: AgentCoordinator.swift
      - path: PerformanceOptimizer.swift
      - path: AppStorePrep.swift
      - path: SecurityManager.swift
      - path: LaunchPrep.swift
      - path: AuthManager.swift
      - path: DataExportManager.swift
      - path: Persistence.swift
      - path: NotificationManager.swift
      - path: SettingsView.swift
      - path: LoginView.swift
      - path: ChartView.swift
      - path: UIHelpers.swift
      - path: BaseAgent.swift
      - path: TradingData+CoreDataProperties.swift
      - path: TradingData.swift
      - path: PatternRecognitionEngine.swift
      - path: TradeSuggestionManager.swift
      - path: TradeSuggestionView.swift
      - path: TradeSuggestionAlert.swift
      - path: TradeSuggestionExtensions.swift
      - path: NIFTYOptionsDataModels.swift
      - path: NIFTYOptionsDataProvider.swift
      - path: IntradayPatternEngine.swift
      - path: HistoricalTrainingManager.swift
      - path: AITradingOrchestrator.swift
      - path: OptionsOrderExecutor.swift
      - path: NIFTYOptionsDashboard.swift
      - path: AIControlCenterView.swift
      - path: PatternScannerView.swift
      - path: RiskManagementDashboard.swift
      - path: PerformanceAnalyticsView.swift
      - path: TechnicalIndicatorsManager.swift
      - path: TimeframeDataManager.swift
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        VALID_ARCHS: arm64 x86_64
        PRODUCT_BUNDLE_IDENTIFIER: com.example.iOS-Trading-App
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 54Z85P52PZ
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_STYLE: Manual
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
        Release:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 54Z85P52PZ

  iOS-Trading-AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: UnitTests.swift
      - path: IntegrationTests.swift
      - path: UATTests.swift
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
    dependencies:
      - target: iOS-Trading-App