name: iOS-Trading-App
options:
  bundleIdPrefix: com.example

targets:
  iOS-Trading-App:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utils
      - path: Agents
      - path: Analytics
      - path: Trading
      
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        VALID_ARCHS: arm64 x86_64
        PRODUCT_BUNDLE_IDENTIFIER: com.example.iOS-Trading-App
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 54Z85P52PZ
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_STYLE: Manual
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
        Release:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 54Z85P52PZ

  iOS-Trading-AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
    dependencies:
      - target: iOS-Trading-App