name: iOS-Trading-App
options:
  bundleIdPrefix: com.example

targets:
  iOS-Trading-App:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
      - path: Core/Protocols
      - path: Core/Models
      - path: Core/Extensions
      - path: Data/Providers
      - path: Data/Managers
      - path: Data/Persistence
      - path: BusinessLogic/Engines
      - path: BusinessLogic/Orchestrators
      - path: BusinessLogic/Analyzers
      - path: Presentation/Views
      - path: Presentation/ViewModels
      - path: Presentation/Components
      - path: Services/Networking
      - path: Services/Notifications
      - path: Services/Analytics
      - path: Utilities
      - path: Shared/Models
      
    dependencies:
      - target: SharedPatternModels
      
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        VALID_ARCHS: arm64 x86_64
        PRODUCT_BUNDLE_IDENTIFIER: com.example.iOS-Trading-App
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 54Z85P52PZ
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_STYLE: Manual
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
        Release:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 54Z85P52PZ

  SharedPatternModels:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Shared/Models
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SharedPatternModels
        GENERATE_INFOPLIST_FILE: YES

  iOS-Trading-AppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: iOS-Trading-App